### ISSUE TITLE
Box adoption in the wild

### ISSUE THREAD

**Issue by theofidry** [box-project/box#19]
### Untouched

- [ ] [php-translation](https://github.com/php-translation/cli)
- [ ] [psh](https://github.com/shopwareLabs/psh)
- [ ] [PHPUnit](https://github.com/sebastianbergmann/phpunit)
- [ ] [phpmetrics](https://github.com/phpmetrics/PhpMetrics/)
- [ ] [paragonie/random_compat](https://github.com/paragonie/random_compat)
- [ ] [phpbrew/Onion](https://github.com/phpbrew/Onion)
- [ ] [facile-it/paraunit](https://github.com/facile-it/paraunit)
- [ ] [maglnet/ComposerRequireChecker](https://github.com/maglnet/ComposerRequireChecker)

### In Progress

- [ ] [deprecation-detector](https://github.com/sensiolabs-de/deprecation-detector) ([#146](https://github.com/sensiolabs-de/deprecation-detector/pull/146))
- [ ] [phpdoc-to-typehint](https://github.com/dunglas/phpdoc-to-typehint) ([#34](https://github.com/dunglas/phpdoc-to-typehint/pull/34))
- [ ] [symfonycorp/insight](https://github.com/symfonycorp/insight) ([#79](https://github.com/symfonycorp/insight/pull/79))
- [ ] [pdepend/pdepend](https://github.com/pdepend/pdepend) ([#372](https://github.com/pdepend/pdepend/pull/372))
- ~~[sensiolabs/security-checker](https://github.com/sensiolabs/security-checker)~~ (will likely be a Go binary in the future)
- [ ] [phpmd/phpmd](https://github.com/phpmd/phpmd) [[jakzal/phpmd#1](https://github.com/jakzal/phpmd/pull/1)]

### Done

- [x] [box](https://github.com/humbug/box)
- [x] [php-scoper](https://github.com/humbug/php-scoper)
- [x] [infection](https://github.com/infection/infection)
- [x] [psalm](https://github.com/vimeo/psalm) ([#656](https://github.com/vimeo/psalm/pull/656))
- [x] [psysh](https://github.com/bobthecow/psysh) ([#488](https://github.com/bobthecow/psysh/pull/488))
- [x] [deptrac](https://github.com/sensiolabs-de/deptrac) ([#178](https://github.com/sensiolabs-de/deptrac/pull/178))
- [x] [laravel-zero/laravel-zero](https://github.com/laravel-zero/laravel-zero)
- [x] [schema-generator](https://github.com/api-platform/schema-generator)
- [x] [doctrine/migrations](https://github.com/doctrine/migrations) ([#691](https://github.com/doctrine/migrations/pull/691))
- [x] [phpstan](https://github.com/phpstan/phpstan)
- [x] [llaville/php-reflect](https://github.com/llaville/php-reflect) ([#28](https://github.com/llaville/php-reflect/issues/28))
- [x] [llaville/umlwriter](https://github.com/llaville/umlwriter) ([086fee15](https://github.com/llaville/umlwriter/commit/086fee1528beb104e385785fde0d92f62c07c294))
- [x] [llaville/php-compat-info](https://github.com/llaville/php-compat-info) ([6faabf7](https://github.com/llaville/php-compat-info/commit/6faabf72313c962adb256c311d1e6bc086ba08de))
- [x] [paratestphp/paratest](https://github.com/paratestphp/paratest) ([#386](https://github.com/paratestphp/paratest/pull/386))
- [x] [cakephp/phinx](https://github.com/cakephp/phinx) ([#1522](https://github.com/cakephp/phinx/pull/1522))
- [x] [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) ([#3726](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/3726))
- [x] [scrutinizer-ci/ocular](https://github.com/scrutinizer-ci/ocular/)([#43](https://github.com/scrutinizer-ci/ocular/pull/43))
- [x] [dmytro-demchyna/schema-keeper](https://github.com/dmytro-demchyna/schema-keeper)
- [x] [phpro/grumphp](https://github.com/phpro/grumphp-shim)
- [x] [phpDocumentor/phpDocumentor2](https://github.com/phpDocumentor/phpDocumentor2)
- [x] [phpbrew](https://github.com/phpbrew/phpbrew)([#1082](https://github.com/phpbrew/phpbrew/pull/1082))

**Comment by bobthecow** [comment]
Pull request?

**Comment by llaville** [comment]
PHP_Reflect 4.3 has just adopted Box v3, see https://github.com/llaville/php-reflect/issues/28#issuecomment-441425092, and will be officially released in next minutes.

**Comment by theofidry** [comment]
awesome, added it! :)

**Comment by llaville** [comment]
I'm not really sure if it's the best usage, with such [contents](https://github.com/llaville/umlwriter/commit/086fee1528beb104e385785fde0d92f62c07c294), but UmlWriter 1.3 is the next to support Box v3

**Comment by theofidry** [comment]
updated :)

**Comment by llaville** [comment]
PHP_CompatInfo 5.1.0 (stable) that will be released in next hour, already support box v3 ; see commit https://github.com/llaville/php-compat-info/commit/6faabf72313c962adb256c311d1e6bc086ba08de

**Comment by jakzal** [comment]
Re phpmd i've done the work: https://github.com/jakzal/phpmd/pull/1

However, I haven't submitted an upstream PR yet, as I'm not sure if project has an active maintainer: https://github.com/phpmd/phpmd/issues/603

**Comment by jaapio** [comment]
phpdocumentor has switched to this repo.

**Comment by theofidry** [comment]
@jaapio nice! Moved it down to the list :)
